AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reddit-filter

  Sample SAM Template for reddit-filter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  RedditEntryTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: RedditEntry
      PrimaryKey: 
        Name: entry_url
        Type: String
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Timeout: 60
      Runtime: python3.9
      Architectures: ["arm64"]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RedditEntryTable
      Events:
        TeikiJikko:
          Type: Schedule
          Properties:
            Schedule: rate(4 hours)

Outputs:
  RedditEntryTable:
    Description: "Reddit Entry Table Name"
    Value: !Ref RedditEntryTable
  TeikiJikkoEvent:
    Description: "定期実行イベント"
    Value: !Ref HelloWorldFunctionTeikiJikko
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
