AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reddit-filter

  Sample SAM Template for reddit-filter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    MemorySize: 128
    Timeout: 60
    Runtime: python3.9
    Architectures: ["arm64"]
    Environment:
      Variables:
        TABLE_NAME: !Ref RedditEntryTable
        BUCKET_NAME: !Ref RedditFeedBucket

Resources:
  # エントリー保存用テーブル
  RedditEntryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RedditEntry
      AttributeDefinitions:
        - AttributeName: entry_url
          AttributeType: S
      KeySchema:
        - AttributeName: entry_url
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttlttl
        Enabled: true
      BillingMode: PAY_PER_REQUEST

  # RSS取得関数
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RedditEntryTable
      Events:
        TeikiJikko:
          Type: Schedule
          Properties:
            Schedule: rate(4 hours)
  # フィード生成関数
  GenerateFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app_generate_feed.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref RedditFeedBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref RedditEntryTable
      Events:
        TeikiJikko:
          Type: Schedule
          Properties:
            Schedule: cron(0 21 * * ? *) # 6:00 JST
  # フィード保存用バケット
  RedditFeedBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
  RedditFeedBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref RedditFeedBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${RedditFeedBucket}/public/*'

Outputs:
  RedditFeedBucket:
    Description: "Reddit Feed Bucket Name"
    Value: !Ref RedditFeedBucket
  RedditEntryTable:
    Description: "Reddit Entry Table Name"
    Value: !Ref RedditEntryTable
  TeikiJikkoEvent:
    Description: "定期実行イベント"
    Value: !Ref HelloWorldFunctionTeikiJikko
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
